# 10. 예외처리

## 1.구문오류와 예외

### 구문오류

* 오타나 문법적으로 필수적인 요소가 빠지진 않았는지 찾아 재 코딩 해야함.

### 예외

* 문법적인 문제는 없는데 실행 중에 예기치 않게 발생함.
  * index error 
  * ...etc

## 2.예외 처리 방법

* 예외 발생 시 해결방법
  1. if 문을 이용한 예외의 처리 -> 정상적인 흐름을 제어할 경우에만 사용
  2. try ~ except 문을 이용한 예외의 처리
  3. try ~ except ~ else 문을 이용한 예외의 처리
  4. try ~ except ~ else ~ finally 문을 이용한 예외의 처리



* **if 문을 이용한 예외의 처리**

```python
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

if width.isdigit() and height.isdigit():
    area = int(width) * int(height)				#isdigit()의 반환값이 True일 경우 실행
    print("{0} x {1} = {2}".format(width, height, area))
else:
    print("숫자가 아닌 값이 입력되었습니다.")
   
print("프로그램을 종료합니다...")

```

***indigit() : 숫자문자인 경우 True반환, 문자열이 입력된 경우 False반환



* 예외 발생 시 해결 방법

  try ~ except 문 : 예외가 발생했을 때 처리

  try ~ except ~ else 문:  예외가 발생했을 때 처리, 예외가 발생하지 않았을때

  try ~ except ~ else ~ finally 문: 예외가 발생했을때 처리, 예외가 발생하지 않았을때, 예외 발생과 상관없이 실행

  

* try ~ except 문

```python
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

try:
    area = int(width) * int(height)
    print("{0} X {1] = {2}".format(width, height, area))
except:
    print("숫자가 아닌 값이 입력되었습니다.") #예
    print("{0} X {1} = {2}".format(width, height, area))
print("프로그램을 종료합니다...")
```

만약 int()변환함수가 타입변환하는 과정에서 ValueError 가 발생한다면 -> except문 을 수행한다.



* try ~ except ~ else 문

```python
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

try:
    area = int(width) * int(height)
except:
    print("숫자가 아닌 값이 입력되었습니다.") #예외 발생시 실행
else:
    print("{0} X {1} = {2}".format(width, height, area))
    #예외가 발생하지 않는 경우 실행
print("프로그램을 종료합니다...")
```

예외상황이 발생된다면 except문 실행.

숫자 입력 시 예외가 발생하지 않아 else문 실행.



* try ~ except ~ else ~ finally 문을 이용한 예외의 처리

```python
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

try:
    area = int(width) * int(height)
except:
    print("숫자가 아닌 값이 입력되었습니다.") #예외 발생 시 실행
else:
    print("{0} X {1} = {2}".format(width, height, area)) #예외가 발생하지 않는 경우 실행
finally:
    print("finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.")
print("프로그램을 종료합니다...")
```

예외 상황이 발생되어 except문 실행

finally 문은 예외 발생 여부와 상관없이 실행됨.



## 03 예외 객체

### 예외 객체

코드를 실행 중 오류가 발생하면 만들어진 것으로, 오류 발생과 관련한 정보를 가지고 있음.



* 예외 객체를 참조해 예외 객체의 타입과 오류메시지를 확인

```python
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")
height = input("높이를 입력하세요: ")
area = 0

try:
    area = int(width) * int(height)
except Exception as ex:
    print("{0}: {1}".format(type(ex), ex)) #ex로 참조
else:
    print("{0} X {1} = {2}".format(width, height, area)) 
finally:
    print("finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.")
print("프로그램을 종료합니다...")
```



* 다중 except 문을 이용한 예외 객체에 따른 처리의 분기

```python
print("나누기 연산의 결과를 구해봅시다.")

x, y, result = 0, 0, 0

try:
    x = int(input("피제수를 입력하세요: "))
    y = int(input("제수를 입력하세요: "))	   #y에 0 저장되어있을 경우 제수가 0이되어
    										#ZeroDivision Error 발생
    result = x / y							#숫자 문자형식이 아닐경우 ValueError발생
    
except ValueError as ve:						#try문에서 ValueError 발생 시
    print("입력 값은 반드시 숫자를 사용해야 합니다.") #ValueError as ve 코드를 사용해
    print("{0}: {1}".format(type(ve), ve))		#except문의 블록에서 ve로 참조.
    
except ZeroDivisionError as ze:				#try문에서 ZeroDivisionError 발생시
    print("제수로 0을 사용할 수 없습니다.")		#ZeroDivisionError 이외의 상황이
    print("{0}: {1}". format(type(ze), ze)) #발생 0시

except Exception as ex:
    print("예상치 못한 예외가 발생했습니다.")  #try문에서 ValueError, ZeroDivision
    print("{0}: {1}".format(type(ex), ex))#Error이외의 상황이 발생시

else:
    print("{0} / {1}".format(x, y, result))
    
finally:
    print("finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.")
```

try 문에서 ValueError가 발생하므로 첫 번째 except문 실행.

=> except ValueError as ve:

​			print("입력 값은 반드시 숫자를 사용해야 합니다.")

​			print("{0}: {1}".format(type(ve), ve))



try 문에서 ZeroDivisionError가 발생하므로 두 번째 except 문 실행

except ZeroDivisionError as ze:

​		print("제수로 0을 사용할 수 없습니다.")

​		print("{0}: {1}".format(type(ze),ze))



[결과]

나누기 연산의 결과를 구해봅시다.

피제수를 입력하세요: 5

제수를 입력하세요: 2

5 / 2 = 2.5

finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.

프로그램을 종료합니다...



try 문에서 예외 발생하지 않음 -> else 문 수행 

`else:`

  `print("{0}/{1}={2}".format(x, y, resul))`



## 04 강제로 예외를 발생시키는 방법

* 강제 예외 발생 : 특정 조건에서 예외 객체를 만들어 예외를 일으킬 수 있음.

```python
def calc_area(w, h):				#w와 h를 매개변수로 사용해 사각형의 면적 반환
    if w.isdigit() and h.isdigit(): #w와 h가 숫자 문자 형식의 문자열인지 검사
        return int(w) * int(h)	# 숫자 문자 형식의 문자열일 경우 int()함수로 정수변환후
    else:						# 곱셈 연산의 결과 반환
        raise ValueError("숫자가 아닌 값이 입력되었습니다.")
        # raise 문을 이용해 강제로 ValueError 예외 상황을 일으킴.
print("사각형의 면적을 구해봅시다.")

width = input("폭을 입력하세요: ")		#표준입력으로 입력된 값 저장
height = input("높이를 입력하세요: ")   #표준입력으로 입력된 값 저장

try:
    area = calc_area(width, height) # 면적 값을 구해 변수 area에 저장.
    #인자로 전달딘 갑싱 숫자 형식의 문자열이 아닐 경우 ValueError 예외를 일으킴.

except ValueError as ve:					#ValueError예외 발생 시 
    print("{0}: {1}".format(type(ve), ve)) #예외 객체를 ValueError as ve 코드를
											#사용해 except문의 블록에서 ve로 참조.
except Exception as ex:					   #ValueError이외의 예외 상황 발생 시
    print("{0}: {1}".format(type(ex), ex)) #-예외 객체를 Exception as ex 코드를 사
    									   #용해 except 문의 블록에서 ex로 참조.
else:
    print("{0} X {1} = {2}".format(width, height, area))
    
finally:
    print("finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.")

print("프로그램을 종료합니다...")
```

[결과]

사각형의 면적을 구해봅시다.

폭을 입력하세요 : 5

높이를 입력하세요 : 10				=>raise문으로 인해 강제로 ValueError 예외 상황 발생.

<class 'ValueError'>: 숫자가 아닌 값이 입력되었습니다.    =>ValueError() 생성자 함수의 인자로 전달

finally 코드 블록은 예외 발생 여부에 상관없이 실행됩니다.

프로그램을 종료합니다...



## 예외처리 기능을 가진 프로그램 만들기

* 사용자로부터 인덱스를 입력받아 숫자로 변환하는 함수

```python
def input_index():
    num = 0
    try:
        num = int(input("인덱스로 사용할 숫자를 입력하세요: "))
    except ValueError as exception:
        raise exception #예외처리없이 함수를 호출한 코드 전달
    else:
        return num

data_list = list(range(1, 11))
print("data_list: {0}".format(data_list))

try:
	num = int(input("인덱스로 사용할 숫자를 입력하세요: "))
	print("[{0}]: {1}".format(num1, data_list[num1])) # indexError발생할수도.,
													#value에러도 발생할 수도.try씀
except IndexError as exception:
    print(exception)
except ValueError as exception:
    print(exception)
except Exception as exception:
    print(exception)						#함수를 활용한 예외처리!

```

